### PR TITLE
initial changes for fork of v2.x

### PR DESCRIPTION
**Pull request by hppritcha**
@jsquyres 
Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by lanl-ompi** [comment]
@rhc54

**Comment by rhc54** [comment]
:+1:

**Comment by jsquyres** [comment]
Can't merge until we actually have a 2.x branch.

**Comment by hppritcha** [comment]
i'll be on planes most of the rest of the day so if you could merge in that would be great.
I think the directories on jaguar are set, but you'll double check...

**Pull request merged**
