### PR TITLE
members: Update Intel logo

### PR DESCRIPTION
**Pull request by wesbland**
Update to Intel logo as published in August, 2020.

Signed-off-by: Wesley Bland <wesley.bland@intel.com>

### CODE REVIEW

**Review by jsquyres — CHANGES_REQUESTED** [review]
Please size the image down to 150xWhatever_preserves_your_aspect_ratio.  Thanks

**Comment by wesbland** [comment]
Oops. Sorry about that. Should be correct now I hope.

**Comment by wesbland** [comment]
@rhc54 Do you not like the new Intel logo or is there an issue with the PR?

**Comment by rhc54** [comment]
😆 just a commentary on the new logo - no issue with what you did 😄

**Comment by wesbland** [comment]
Hey, when I haven't contributed anything to OMPI in almost a decade, seeing a 👎 unnerves a guy. 😄

**Comment by rhc54** [comment]
SORRY! Just don't think much of that new logo 😛

**Review by jsquyres — APPROVED** [review]

**Pull request merged**
