### PR TITLE
Stop indexing old man pages

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres google still points to old versions of the man pages.
googlebot will no more crawl them, because of the `robots.txt`, but they will not be removed from google search engine. this pr adds `<META name="googlebot" content="noindex">` when `$noindex` is set, so when googlebot crawls them, they will be removed from the search engine.

**Comment by jsquyres** [comment]
Good idea.

Instead of editing every single man page, however, can we put some URI-based logic in header.inc, or something?  E.g., if the URI is in the man page dir for less than 2.0, set `$noindex` to true?

A centralized approach will be much more scalable for when we want Google to stop indexing future versions.

**Comment by ggouaillardet** [comment]
ok, i updated the PR and used a regex.
note the regex is not `^/doc/v1` but `/doc/v1` since the use of `$topdir` suggests the site does not have to be at the rootdir of the web server.

**Comment by jsquyres** [comment]
Thanks!

**Comment by bgoglin** [comment]
Random question: Isn't this regexp matching hwloc doc too? We'd want to keep the latest projects/hwloc/doc/v1.11* in google :)

**Comment by ggouaillardet** [comment]
the regexp does match the hwloc doc, but since you do not include `$topdir/doc/nav.inc`, the meta directive is not generated.

**Pull request merged**
