### PR TITLE
remove references to the legacy ompi-release repository

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by jsquyres** [comment]
Fixes https://github.com/open-mpi/ompi/issues/2153.

**Comment by ggouaillardet** [comment]
@jsquyres is the web site auto magically updated when a commit is pushed ?
If yes, how long should it take before the update goes live ?

**Comment by jsquyres** [comment]
Yes, the web site has a crontab that runs "git pull --rebase" periodically.  IIRC, it's every hour -- but it could also be as frequently as every 15 mins...?

I saw the cron output email mail go by recently (showing the output of the fast forward pull); it should be live on the site already.

**Comment by ggouaillardet** [comment]
Ok, it is live now :-)

**Pull request merged**
