### PR TITLE
faq/tcp: add an entry related to 10GbE networks and faster

### PR DESCRIPTION
**Pull request by ggouaillardet**
- set send and receive buffers size to zero
- try multiple links

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@bwbarrett @bosilca can you please double check this ?

this is related to https://www.mail-archive.com/users@lists.open-mpi.org/msg31283.html

if there are some recommended settings for AWS, they can be added and/or linked too

**Comment by bgoglin** [comment]
I don't understand "Open MPI < v2.0.3 or > v2.1.2".

**Comment by ggouaillardet** [comment]
oops, that is a pretty dumb typo i will fix right away

**Comment by bosilca** [comment]
I would rather be more specific, and not tie this capability to a specific version of OMPI, but instead talk about the real reason why this settings are not necessary anymore. We should say that in modern version of the Linux kernel, setting the TCP send and receive buffers is a unnecessary operation that can lead to inefficiencies. We suggest users to check their TCP buffer sizes using ```ompi_info --param btl tcp -l 4``` and make sure that btl_tcp_sndbuf and btl_tcp_rcvbuf are set to 0. Starting from Open MPI 2.0.3 this are the default settings.

**Comment by bwbarrett** [comment]
I agree with George.  Also, the btl_num_links option doesn't work correctly.  We need to sort that out before we suggest it in a FAQ.

**Comment by ggouaillardet** [comment]
i updated this PR, please double check the wording

**Comment by gpaulsen** [comment]
@ggouaillardet, @bwbarrett @bosilca: Is this still relevant?  Should we pull it in, or are we still waiting on some fixes?

**Comment by bwbarrett** [comment]
We need to test, because I think multilink works in 4.0.  Either way, I think adding the multilinks answer is a really bad look for Open MPI.

**Comment by bosilca** [comment]
We need closure on this topic. I just added this topic to the developer's meeting agenda.

**Comment by bwbarrett** [comment]
Closing in favor of https://github.com/open-mpi/ompi-www/pull/111

**Pull request closed without merging**
